services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sampleandtest
    ports:
      - "5173:5173"
    environment:
      - NODE_VERSION=v23.6.0
    tty: true
